KERNEL_SRC ?= /lib/modules/$(shell uname -r)/build

KBUILD_OPTIONS := WLAN_ROOT=$(PWD)
KBUILD_OPTIONS += MODNAME?=wlan

# Determine if the driver license is Open source or proprietary
# This is determined under the assumption that LICENSE doesn't change.
# Please change here if driver license text changes.
LICENSE_FILE ?= $(PWD)/$(WLAN_ROOT)/CORE/HDD/src/wlan_hdd_main.c
WLAN_OPEN_SOURCE = $(shell if grep -q "MODULE_LICENSE(\"Dual BSD/GPL\")" \
		$(LICENSE_FILE); then echo 1; else echo 0; fi)

KBUILD_EXTRA := CONFIG_LINUX_QCMBR=y
KBUILD_EXTRA += CONFIG_PER_VDEV_TX_DESC_POOL=1
KBUILD_EXTRA += SAP_AUTH_OFFLOAD=1
KBUILD_EXTRA += CONFIG_QCA_LL_TX_FLOW_CT=1
KBUILD_EXTRA += CONFIG_WLAN_FEATURE_FILS=y
KBUILD_EXTRA += CONFIG_FEATURE_COEX_PTA_CONFIG_ENABLE=y
KBUILD_EXTRA += CONFIG_QCA_SUPPORT_TXRX_DRIVER_TCP_DEL_ACK=y
KBUILD_EXTRA += CONFIG_WLAN_WAPI_MODE_11AC_DISABLE=y
KBUILD_EXTRA += CONFIG_LINUX_QCMBR=y
KBUILD_EXTRA += CONFIG_PMF_SUPPORT=y
KBUILD_EXTRA += CONFIG_CFG80211_INTERNAL_REGDB=y
KBUILD_EXTRA += BUILD_DRIVERFW_TOLOCAL=y
KBUILD_EXTRA += CONFIG_NO_USE_BACKPORTS=y
KBUILD_EXTRA += CONFIG_CFG80211_DEPEND_ON_KERNEL=y
KBUILD_EXTRA += WLAN_OPEN_SOURCE=1

KBUILD_EXTRA += CONFIG_CLD_HL_USB_CORE=y
#KBUILD_EXTRA := CONFIG_CLD_HL_SDIO_CORE=y

#By default build for CLD
WLAN_SELECT := CONFIG_QCA_CLD_WLAN=m
KBUILD_OPTIONS += CONFIG_QCA_WIFI_ISOC=0
KBUILD_OPTIONS += CONFIG_QCA_WIFI_2_0=1
KBUILD_OPTIONS += $(WLAN_SELECT)
KBUILD_OPTIONS += WLAN_OPEN_SOURCE=$(WLAN_OPEN_SOURCE)
KBUILD_OPTIONS += $(KBUILD_EXTRA) # Extra config if any

.NOTPARALLEL:

all:
	$(MAKE) -C $(KERNEL_SRC) M=$(shell pwd) modules $(KBUILD_OPTIONS)

modules_install:
	$(MAKE) INSTALL_MOD_STRIP=1 -C $(KERNEL_SRC) M=$(shell pwd) modules_install

clean:
	$(MAKE) -C $(KERNEL_SRC) M=$(PWD) clean
